In [1]:
import numpy as np

In [8]:
x = np.array([1.0 + 1.0j, 0.0 + 1.0j]).reshape(-1, 1); display(x)

array([[1.+1.j],
       [0.+1.j]])

&#x1F9E8; This is not working

In [12]:
np.fft.fft(x)

array([[1.+1.j],
       [0.+1.j]])

- [ ] [What is the difference between the return of fft / fft2 applied to a matrix?](https://stackoverflow.com/questions/21799600/what-is-the-difference-between-the-return-of-fft-fft2-applied-to-a-matrix)

In [15]:
np.fft.fft2(x)

array([[1.+2.j],
       [1.+0.j]])

In [16]:
np.fft.fftshift(x)

array([[0.+1.j],
       [1.+1.j]])